function topShell(content){return `
<div class="govbar"><div class="govbar-inner"><span>${t('Government of Rajasthan','राजस्थान सरकार')} · ${t('Department of Agriculture','कृषि विभाग')}</span><div class="tools"><button class="tiny-btn" onclick="font(-1)">A−</button><button class="tiny-btn" onclick="font(0)">A</button><button class="tiny-btn" onclick="font(1)">A+</button><button class="tiny-btn" onclick="contrast()">◐ ${t('Contrast','कॉन्ट्रास्ट')}</button><button class="tiny-btn" onclick="toggleLang()">${state.lang==='en'?'हिन्दी':'English'}</button></div></div></div>
<header class="mast"><div class="mast-inner"><div class="brand"><div class="state-mark">RJ</div><div class="brand-copy"><strong>${t('Department of Agriculture','कृषि विभाग')}</strong><span>${t('Government of Rajasthan','राजस्थान सरकार')} · Citizen Services</span></div></div><div class="product-lockup"><b>RajKisan One</b><span>${t('Agriculture Digital Front Door','कृषि डिजिटल फ्रंट डोर')} · <em class="mvp-mark">MVP PROTOTYPE</em></span></div><button class="sso-chip" onclick="openSSO()">${I.shield} ${t('RajSSO / Jan Aadhaar','RajSSO / जन आधार')}<small>${t('Sandbox session','सैंडबॉक्स सत्र')}</small></button></div></header>
<nav class="mainnav" aria-label="Primary"><div class="mainnav-inner">
${nav('home',I.home,t('Home','मुख्य'))}${nav('services',I.services,t('Services','सेवाएँ'))}${nav('farm',I.farm,t('My Agriculture','मेरा कृषि'))}${nav('map',I.map,t('GIS & Centres','मानचित्र'))}${nav('analytics',I.analytics,t('Department Insights','विभागीय अंतर्दृष्टि'))}${nav('integrations',I.integrations,t('DPI Integrations','DPI एकीकरण'))}${nav('cms',I.cms,'CMS & GIGW')}${nav('edge',I.edge,'SUTRA Field')}
<div class="nav-spacer"></div><button class="navbtn emph" onclick="startDemo()">▶ ${t('Evaluator Demo','मूल्यांकन डेमो')}</button></div></nav>
<main id="main">${state.demo?demoBanner():''}${content}</main>${assistant()}${footer()}${modals()}`}
function nav(r,ic,label){return `<button class="navbtn ${state.route===r?'active':''}" onclick="go('${r}')"><b>${ic}</b><span>${label}</span></button>`}
function page(title,sub,body){return `<div class="page"><div class="breadcrumb">${t('Home','मुख्य')} / <b>${title}</b></div>${sub?`<div class="section-head" style="margin-top:0"><div><h2>${title}</h2><p>${sub}</p></div></div>`:''}${body}</div>`}
function demoBanner(){return `<div class="page" style="padding-bottom:0"><div class="demo-banner"><div><b>${t('Evaluator Guided Demo','मूल्यांकन निर्देशित डेमो')} · ${state.demoStep+1}/8</b><span>${demoText()[state.demoStep]}</span></div><div class="steps">${Array.from({length:8},(_,i)=>`<i class="stepdot ${i===state.demoStep?'on':''}"></i>`).join('')}</div><button class="btn sm" onclick="demoNext()">${state.demoStep===7?t('Finish','समाप्त'):t('Next proof','अगला')}</button><button class="btn sm ghost" style="color:white;border-color:#466b91" onclick="endDemo()">×</button></div></div>`}
function demoText(){return [t('Citizen starts with intent, not department hierarchy.','नागरिक विभागीय पदानुक्रम नहीं, अपने कार्य से शुरू करता है।'),t('Run deterministic scheme eligibility with explainable criteria.','स्पष्ट नियमों से योजना पात्रता जाँचें।'),t('Reuse verified documents; upload only what is missing.','सत्यापित दस्तावेज़ पुनः उपयोग करें।'),t('Track an application as a citizen-readable service timeline.','आवेदन को स्पष्ट सेवा टाइमलाइन में ट्रैक करें।'),t('Use GIS for nearby support and district service intelligence.','GIS से निकट सहायता और जिला सेवा स्थिति देखें।'),t('Close the loop with funnel, search and feedback analytics.','फनल, खोज और प्रतिक्रिया से सुधार चक्र पूरा करें।'),t('Show every integration truth state; never fake Government credentials.','हर एकीकरण की वास्तविक स्थिति स्पष्ट दिखाएँ।'),t('Selective SUTRA-ID Edge extends the same contracts to low-connectivity field access.','SUTRA-ID Edge वही सेवाएँ कम-कनेक्टिविटी क्षेत्रों तक पहुँचाता है।')];}
