async function eligResult(){
  const body=document.getElementById('eligBody');
  body.innerHTML=`<div class="wizard-steps"><span class="on"></span><span class="on"></span><span></span></div><div class="card card-pad" style="text-align:center"><div class="splash-loader" style="background:#dbe8f5;margin:8px auto 16px"><i style="background:var(--gov)"></i></div><b>${t('Evaluating versioned scheme rules…','संस्करणित योजना नियमों का मूल्यांकन…')}</b><p style="font-size:11px;color:var(--muted)">${t('No AI model is authorised to approve or deny the benefit.','किसी AI मॉडल को लाभ स्वीकृत या अस्वीकृत करने का अधिकार नहीं है।')}</p></div>`;
  let result={receipt:'RKO-LOCAL-DEMO',ruleVersion:'demo-2026.08.29',result:'POTENTIALLY_ELIGIBLE'};
  try{
    const r=await fetch('/api/eligibility',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({district:'Jaipur',landholdingHa:1.5,farmerRegistryLinked:true})});
    if(r.ok) result=await r.json(); else throw new Error('sandbox endpoint unavailable');
  }catch(_){ await new Promise(resolve=>setTimeout(resolve,650)); }
  const good=result.result==='POTENTIALLY_ELIGIBLE';
  body.innerHTML=`<div class="wizard-steps"><span class="on"></span><span class="on"></span><span class="on"></span></div><div class="elig-result"><span class="pill ok">RULE ENGINE · ${esc(result.ruleVersion||'DEMO')}</span><h3>${good?t('Potentially eligible','संभावित रूप से पात्र'):t('Needs review','समीक्षा आवश्यक')}</h3><p style="font-size:12px;color:#456557">${t('The demo profile meets all configured pre-check conditions. Final eligibility and sanction remain with the authoritative department workflow.','डेमो प्रोफ़ाइल सभी कॉन्फ़िगर पूर्व-जाँच शर्तें पूरी करती है। अंतिम पात्रता और स्वीकृति अधिकृत विभागीय वर्कफ़्लो में रहेगी।')}</p><div class="checks"><div class="check"><b>✓</b> Rajasthan resident context</div><div class="check"><b>✓</b> Eligible district</div><div class="check"><b>✓</b> Landholding rule</div><div class="check"><b>✓</b> Farmer Registry linked</div><div class="check"><b>✓</b> Service window available</div><div class="check"><b>✓</b> Required category data present</div></div><div class="notice success" style="margin:10px 0"><b>Decision receipt:</b> ${esc(result.receipt||'RKO-LOCAL-DEMO')} · non-statutory</div><button class="btn primary" onclick="go('farm');closeModal()">${t('Prepare documents & continue','दस्तावेज़ तैयार करें और आगे बढ़ें')}</button> <button class="btn" onclick="toast('${t('Official source/version metadata opened','आधिकारिक स्रोत/संस्करण मेटाडेटा खोला गया')}')">${t('Why this result?','यह परिणाम क्यों?')}</button></div>`;
  state.eligibleDone=true;trackEvent('eligibility_precheck',{result:result.result,ruleVersion:result.ruleVersion})
}
